# Generated by Django 2.1.5 on 2019-01-22 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField()),
                ('purchased', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
